# Generated by Django 5.0.3 on 2024-03-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('link', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
