# Generated by Django 5.0.3 on 2024-03-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iconredessociales_alter_redessociales_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redessociales',
            old_name='nombre',
            new_name='redSocial',
        ),
    ]
