# Generated by Django 5.0.3 on 2024-03-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_redessociales_redsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociales',
            name='redSocial',
        ),
        migrations.DeleteModel(
            name='IconRedesSociales',
        ),
        migrations.DeleteModel(
            name='redesSociales',
        ),
    ]
