# Generated by Django 5.0.3 on 2024-03-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociales',
            name='redSocial',
        ),
        migrations.DeleteModel(
            name='IconRedesSociales',
        ),
        migrations.DeleteModel(
            name='redesSociales',
        ),
    ]
