# Generated by Django 5.0.3 on 2024-03-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconRedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='red social')),
                ('icon', models.ImageField(upload_to='icons_redes_sociales')),
            ],
        ),
        migrations.CreateModel(
            name='redesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('redSocial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redessociales.iconredessociales', verbose_name='red social')),
            ],
        ),
    ]
